"""
Context HTML Renderer — Phase 17A

Renders a deterministic, static, safe HTML document from a context bundle
and optional package-file info dict.

Rules:
- No remote scripts, no remote CSS, no external assets of any kind.
- All user-controlled content is HTML-escaped.
- No JavaScript execution, no inline event handlers.
- Output is deterministic for identical input (no timestamps, no random IDs).
- Uses only Python standard library (html, json, pathlib are already present).
- Note body and section text are rendered inside <pre> blocks (escaped).
- Markdown is NOT parsed into HTML — plain escaped text is displayed.
"""

from __future__ import annotations

import html
import json as _json


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_context_html(
    bundle: dict,
    package_files: dict | None = None,
) -> str:
    """Render a static HTML document from bundle data and optional file-info map.

    Args:
        bundle:        Bundle dict (as returned by generate_bundle / stored in
                       context.json).  Only keys that are present are rendered.
        package_files: Optional dict mapping filename → {"sha256": str,
                       "bytes": int}, as stored in the manifest "files" dict.
                       When provided, a manifest-hash section is included.

    Returns:
        A UTF-8 string containing a complete self-contained HTML5 document.
        The document contains no remote assets and no JavaScript.
    """
    sections: list[str] = [
        _render_artefact_warning(),
        _render_metadata(bundle),
        _render_notes(bundle),
        _render_validation(bundle),
        _render_security(bundle),
        _render_graph(bundle),
        _render_feedback(bundle),
        _render_manifest(package_files),
    ]

    body_html = "\n".join(s for s in sections if s)

    return "\n".join([
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="UTF-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        f"<title>Context Bundle: {_escape(bundle.get('bundle_id', 'unknown'))}</title>",
        _INLINE_STYLE,
        "</head>",
        "<body>",
        f'<h1>Context Bundle: {_escape(bundle.get("bundle_id", "unknown"))}</h1>',
        body_html,
        "</body>",
        "</html>",
    ])


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _escape(value: object) -> str:
    """Return an HTML-escaped string representation of value.

    Converts the value to str first, then applies html.escape so that
    all angle brackets, ampersands and quotes are entity-encoded.
    """
    return html.escape(str(value) if value is not None else "", quote=True)


def _render_artefact_warning() -> str:
    return (
        '<div class="warning">'
        "<strong>Generated artefact warning.</strong> "
        "This HTML file is a generated rendering of an exported context package. "
        "It is not the source of truth. "
        "All knowledge is stored in Markdown vault notes. "
        "Do not edit this file — make changes in the vault instead."
        "</div>"
    )


def _render_metadata(bundle: dict) -> str:
    bundle_id = bundle.get("bundle_id", "")
    vault = bundle.get("vault", "")
    created_at = bundle.get("created_at", "")
    schema_version = bundle.get("manifest", {}).get("schema_version", "")
    validation_status = bundle.get("validation_status", "")
    budget = bundle.get("budget", {})
    warnings = bundle.get("warnings", [])
    filters = bundle.get("filters", {})

    rows: list[str] = [
        _tr("Bundle ID", bundle_id),
        _tr("Vault", vault),
        _tr("Created", created_at),
        _tr("Schema Version", schema_version),
        _tr("Validation Status", validation_status),
        _tr("Note Count", str(budget.get("note_count", len(bundle.get("notes", []))))),
        _tr("Budget Used",
            f"{budget.get('used_chars', 0)} / {budget.get('max_chars', 0)} chars"),
        _tr("Truncated", str(budget.get("truncated", False)).lower()),
        _tr("Filters", _json.dumps(
            {k: v for k, v in sorted(filters.items())},
            ensure_ascii=False,
        ) if filters else "(none)"),
    ]

    warnings_html = ""
    if warnings:
        items = "".join(f"<li>{_escape(w)}</li>" for w in warnings)
        warnings_html = f"<h3>Warnings</h3><ul>{items}</ul>"

    return (
        "<section>"
        "<h2>Bundle Metadata</h2>"
        f'<table class="meta"><tbody>{"".join(rows)}</tbody></table>'
        f"{warnings_html}"
        "</section>"
    )


def _render_notes(bundle: dict) -> str:
    notes = bundle.get("notes", [])
    if not notes:
        return (
            "<section>"
            "<h2>Notes</h2>"
            "<p>(no notes in this bundle)</p>"
            "</section>"
        )

    parts: list[str] = ["<section><h2>Notes</h2>"]
    for note in notes:
        path = note.get("path", "")
        fields = note.get("fields", {})
        sections = note.get("sections", {})
        body = note.get("body", "")
        related = note.get("related", [])

        parts.append(f'<div class="note">')
        parts.append(f"<h3>{_escape(path)}</h3>")

        if fields:
            rows = "".join(
                _tr(k, _escape(_format_value(v)))
                for k, v in sorted(fields.items())
            )
            parts.append(
                f'<table class="fields"><tbody>{rows}</tbody></table>'
            )

        for sec_name, sec_body in sorted(sections.items()):
            parts.append(f"<h4>{_escape(sec_name)}</h4>")
            if sec_body:
                parts.append(f"<pre>{_escape(sec_body.strip())}</pre>")
            else:
                parts.append("<p><em>(section not found)</em></p>")

        if body:
            parts.append("<h4>Full Body</h4>")
            parts.append(f"<pre>{_escape(body.strip())}</pre>")

        if related:
            items = "".join(f"<li>{_escape(r)}</li>" for r in related)
            parts.append(f"<h4>Related</h4><ul>{items}</ul>")

        parts.append("</div>")

    parts.append("</section>")
    return "\n".join(parts)


def _render_validation(bundle: dict) -> str:
    validation_status = bundle.get("validation_status", "unknown")
    warnings = bundle.get("warnings", [])

    parts = [
        "<section>",
        "<h2>Validation</h2>",
        f'<table class="meta"><tbody>',
        _tr("Status", validation_status),
        "</tbody></table>",
    ]

    if warnings:
        items = "".join(f"<li>{_escape(w)}</li>" for w in warnings)
        parts.append(f"<h3>Warnings</h3><ul>{items}</ul>")
    else:
        parts.append("<p>No validation warnings.</p>")

    parts.append("</section>")
    return "\n".join(parts)


def _render_security(bundle: dict) -> str:
    security = bundle.get("security")
    if security is None:
        return (
            "<section>"
            "<h2>Security</h2>"
            "<p>No security scan data is embedded in this HTML artefact. "
            "Run a security scan separately to review security findings.</p>"
            "</section>"
        )

    # Security data is present — render available fields.
    parts = ["<section>", "<h2>Security</h2>"]

    status = security.get("status", "unknown")
    findings_count = len(security.get("findings", []))
    parts.append(
        f'<table class="meta"><tbody>'
        f'{_tr("Scan Status", status)}'
        f'{_tr("Findings", str(findings_count))}'
        f"</tbody></table>"
    )

    findings = security.get("findings", [])
    if findings:
        parts.append("<h3>Findings</h3>")
        for finding in findings:
            if isinstance(finding, dict):
                rows = "".join(
                    _tr(k, _format_value(v))
                    for k, v in sorted(finding.items())
                )
                parts.append(
                    f'<div class="finding"><table class="meta"><tbody>'
                    f"{rows}</tbody></table></div>"
                )
            else:
                parts.append(f"<p>{_escape(str(finding))}</p>")
    else:
        parts.append("<p>No security findings.</p>")

    parts.append("</section>")
    return "\n".join(parts)


def _render_graph(bundle: dict) -> str:
    graph = bundle.get("graph", {})
    if not graph:
        return (
            "<section>"
            "<h2>Graph</h2>"
            "<p>No graph data in this bundle. "
            "See <code>graph.json</code> in the package directory for graph relationships.</p>"
            "</section>"
        )

    related = graph.get("related", {})
    parts = [
        "<section>",
        "<h2>Graph</h2>",
        f"<p>Related note count: {_escape(str(len(related)))}</p>",
    ]

    if related:
        parts.append("<ul>")
        for note_path, rels in sorted(related.items()):
            if isinstance(rels, list):
                rel_items = "".join(
                    f"<li>{_escape(str(r))}</li>" for r in rels
                )
                parts.append(
                    f"<li><strong>{_escape(note_path)}</strong><ul>{rel_items}</ul></li>"
                )
            else:
                parts.append(
                    f"<li><strong>{_escape(note_path)}</strong>: {_escape(str(rels))}</li>"
                )
        parts.append("</ul>")
    else:
        parts.append("<p>No graph relationships recorded for this bundle.</p>")

    parts.append("</section>")
    return "\n".join(parts)


def _render_feedback(bundle: dict) -> str:
    feedback = bundle.get("feedback", {})
    if not feedback:
        return (
            "<section>"
            "<h2>Feedback</h2>"
            "<p>No feedback data in this bundle.</p>"
            "</section>"
        )

    entries = feedback.get("entries", [])
    fb_warnings = feedback.get("warnings", [])

    parts = ["<section>", "<h2>Feedback</h2>"]

    if fb_warnings:
        items = "".join(f"<li>{_escape(w)}</li>" for w in fb_warnings)
        parts.append(f'<div class="warning"><strong>Feedback Warnings:</strong><ul>{items}</ul></div>')

    if entries:
        for entry in entries:
            if isinstance(entry, dict):
                rows = "".join(
                    _tr(k, _format_value(v))
                    for k, v in sorted(entry.items())
                )
                parts.append(
                    f'<div class="feedback-entry"><table class="meta"><tbody>'
                    f"{rows}</tbody></table></div>"
                )
            else:
                parts.append(f"<p>{_escape(str(entry))}</p>")
    else:
        parts.append("<p>No feedback entries.</p>")

    parts.append("</section>")
    return "\n".join(parts)


def _render_manifest(package_files: dict | None) -> str:
    if not package_files:
        return (
            "<section>"
            "<h2>Manifest Hashes</h2>"
            "<p>No manifest file information available.</p>"
            "</section>"
        )

    parts = [
        "<section>",
        "<h2>Manifest Hashes</h2>",
        '<table class="manifest">',
        "<thead><tr>"
        "<th>File</th>"
        "<th>SHA-256</th>"
        "<th>Bytes</th>"
        "</tr></thead>",
        "<tbody>",
    ]

    for fname in sorted(package_files.keys()):
        info = package_files[fname]
        sha = info.get("sha256", "")
        size = info.get("bytes", "")
        parts.append(
            f"<tr>"
            f"<td>{_escape(fname)}</td>"
            f"<td class=\"hash\">{_escape(sha)}</td>"
            f"<td>{_escape(str(size))}</td>"
            f"</tr>"
        )

    parts.append("</tbody></table>")
    parts.append("</section>")
    return "\n".join(parts)


def _tr(label: str, value: str) -> str:
    """Return a two-cell table row with escaped label and value."""
    return f"<tr><th>{_escape(label)}</th><td>{_escape(value)}</td></tr>"


def _format_value(value: object) -> str:
    """Format a frontmatter/dict value as a short string."""
    if isinstance(value, list):
        return ", ".join(_escape(str(v)) for v in value)
    if isinstance(value, dict):
        return _json.dumps(value, ensure_ascii=False)
    return str(value) if value is not None else ""


# ---------------------------------------------------------------------------
# Inline CSS (no external resources)
# ---------------------------------------------------------------------------

_INLINE_STYLE = """\
<style>
  body {
    font-family: sans-serif;
    font-size: 14px;
    line-height: 1.5;
    max-width: 960px;
    margin: 0 auto;
    padding: 1rem 2rem 3rem;
    color: #1a1a1a;
    background: #fff;
  }
  h1 { font-size: 1.4rem; border-bottom: 2px solid #333; padding-bottom: .4rem; }
  h2 { font-size: 1.15rem; margin-top: 2rem; border-bottom: 1px solid #ccc; }
  h3 { font-size: 1rem; margin-top: 1rem; }
  h4 { font-size: .9rem; margin-top: .8rem; color: #555; }
  section { margin-bottom: 2rem; }
  .warning {
    background: #fff3cd;
    border: 1px solid #ffc107;
    border-radius: 4px;
    padding: .6rem 1rem;
    margin-bottom: 1.2rem;
  }
  table.meta, table.fields, table.manifest {
    border-collapse: collapse;
    width: 100%;
    font-size: .9rem;
  }
  table.meta th, table.fields th {
    text-align: left;
    font-weight: normal;
    color: #555;
    padding: .25rem .5rem;
    white-space: nowrap;
    width: 20%;
  }
  table.meta td, table.fields td, table.manifest td, table.manifest th {
    padding: .25rem .5rem;
    border-bottom: 1px solid #eee;
  }
  table.manifest thead th { font-weight: bold; background: #f5f5f5; }
  .hash { font-family: monospace; font-size: .8rem; word-break: break-all; }
  pre {
    background: #f8f8f8;
    border: 1px solid #ddd;
    border-radius: 3px;
    padding: .5rem .75rem;
    white-space: pre-wrap;
    word-break: break-word;
    font-size: .85rem;
    max-height: 20rem;
    overflow-y: auto;
  }
  .note { border: 1px solid #ddd; border-radius: 4px; padding: .75rem 1rem; margin-bottom: 1rem; }
  .note h3 { margin-top: 0; }
  .finding, .feedback-entry {
    border: 1px solid #e0e0e0;
    border-radius: 3px;
    margin-bottom: .5rem;
    padding: .5rem;
  }
  code { background: #f5f5f5; padding: .1em .3em; border-radius: 2px; }
</style>"""
